# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget NLopt::nlopt)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target NLopt::nlopt
add_library(NLopt::nlopt SHARED IMPORTED)

set_target_properties(NLopt::nlopt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "NLOPT_DLL"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/src/api;C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0"
)

# Import target "NLopt::nlopt" for configuration "Debug"
set_property(TARGET NLopt::nlopt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(NLopt::nlopt PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/Debug/nlopt.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/Debug/nlopt.dll"
  )

# Import target "NLopt::nlopt" for configuration "Release"
set_property(TARGET NLopt::nlopt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(NLopt::nlopt PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/Release/nlopt.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/Release/nlopt.dll"
  )

# Import target "NLopt::nlopt" for configuration "MinSizeRel"
set_property(TARGET NLopt::nlopt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(NLopt::nlopt PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/MinSizeRel/nlopt.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/MinSizeRel/nlopt.dll"
  )

# Import target "NLopt::nlopt" for configuration "RelWithDebInfo"
set_property(TARGET NLopt::nlopt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(NLopt::nlopt PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/RelWithDebInfo/nlopt.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/MarcusRainbow/Projects/node-nlopt/nlopt-2.10.0/RelWithDebInfo/nlopt.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
